# Generated by Django 4.1.7 on 2023-03-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countryID', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=200)),
                ('countryValue', models.CharField(max_length=200)),
                ('phone_code', models.IntegerField()),
                ('currency', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('emoji', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('citiesID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('latitude', models.CharField(default='', max_length=200)),
                ('longitude', models.CharField(default='', max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CountryState.countries')),
            ],
        ),
    ]
